name: 💡 Feature request
description: knock에 바라는 기능 / Suggest a knock feature
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: 어떤 문제를 풀고 싶나요? / What problem are you solving?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: 제안 / Proposed solution
  - type: textarea
    id: alt
    attributes:
      label: 대안 / Alternatives (선택)
